services:
  webserver:
    build:
      context: ./bin/webserver
      dockerfile: Dockerfile
    volumes:
      - ./webroot:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-available/
      - ./logs/apache2:/var/log/apache2
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DB_SERVER=${DB_SERVER}
      - HOST_MACHINE_MYSQL_PORT=${HOST_MACHINE_MYSQL_PORT}
      - HOST_MACHINE_PHPMYADMIN_PORT=${HOST_MACHINE_PHPMYADMIN_PORT}
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"  # Map host port 8080 to container port 80
      # - "${HOST_MACHINE_HTTPS_PORT}:443" 

  db:
    image: ${DB_SERVER}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER} 
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - /home/nileshdomah/docker-compose-lamp/.bin/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - /home/nileshdomah/docker-compose-lamp/nginx/ssl:/etc/nginx/ssl  # Ensure this directory contains your SSL certificate and key
  #   ports:
  #     - "80:80"   # Map host port 8080 to container port 80
  #     - "443:443" 
  #   depends_on:
  #     - webserver